export type CourseId = "bsit" | "beed" | "bsed" | "bshm" | "bsentrep" | "bscs" | "bped"
export type YearId = "1st-year" | "2nd-year" | "3rd-year" | "4th-year"
export type BlockId = "block-a" | "block-b" | "block-c" | "block-d" | "block-e" | "block-f"

interface StudentData {
  id: string
  name: string
  image: string
  quote?: string
  honors?: string
  fullName?: string
  nickname?: string
  age?: number
  birthday?: string
  address?: string
  email?: string
  phone?: string
  department?: string
  yearLevel?: string
  courseProgram?: string
  blockSection?: string
  dreamJob?: string
  fatherGuardianName?: string
  motherGuardianName?: string
  socialMediaFacebook?: string
  socialMediaInstagram?: string
  socialMediaTwitter?: string
  sayingMotto?: string
  profilePictureUrl?: string
  achievements?: string[]
  activities?: string[]
}

export const collegeData = {
  bsit: {
    name: "BSIT",
    fullName: "Bachelor of Science in Information Technology",
    years: {
      "1st-year": {
        name: "1st Year",
        blocks: {
          "block-a": {
            name: "Block A",
            schoolYears: {
              "2024-2025": {
                academicYear: "2024-2025",
                advisers: [
                  {
                    id: "prof-smith",
                    name: "Prof. John Smith",
                    image: "/placeholder.svg",
                    quote: "Innovate and create the future.",
                  },
                ],
                students: [
                  {
                    id: "s101",
                    name: "Alice Johnson",
                    fullName: "Alice Marie Johnson",
                    nickname: "Alice",
                    age: 18,
                    birthday: "2006-03-15",
                    address: "123 Tech Street, Toledo City",
                    email: "alice.johnson@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6801",
                    department: "College",
                    yearLevel: "1st Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block A",
                    dreamJob: "Software Developer",
                    fatherGuardianName: "Robert Johnson",
                    motherGuardianName: "Maria Johnson",
                    socialMediaFacebook: "alice.johnson.student",
                    socialMediaInstagram: "@alicejohnson",
                    socialMediaTwitter: "@alice_codes",
                    sayingMotto: "Coding my way to success.",
                    image: "/placeholder.svg",
                    profilePictureUrl: "/placeholder.svg",
                    quote: "Coding my way to success.",
                    honors: "Dean's Lister",
                    achievements: ["Dean's Lister", "Programming Competition Finalist"],
                    activities: ["IT Society Member", "Coding Club"],
                  },
                  {
                    id: "s102",
                    name: "Bob Williams",
                    fullName: "Robert Williams",
                    nickname: "Bob",
                    age: 19,
                    birthday: "2005-07-22",
                    address: "456 Innovation Ave, Toledo City",
                    email: "bob.williams@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6802",
                    department: "College",
                    yearLevel: "1st Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block A",
                    dreamJob: "Web Developer",
                    fatherGuardianName: "John Williams",
                    motherGuardianName: "Sarah Williams",
                    socialMediaFacebook: "bob.williams.dev",
                    socialMediaInstagram: "@bobwilliams",
                    socialMediaTwitter: "@bob_dev",
                    sayingMotto: "Building digital dreams.",
                    image: "/placeholder.svg",
                    profilePictureUrl: "/placeholder.svg",
                    quote: "Building digital dreams.",
                    achievements: ["Web Design Contest Winner"],
                    activities: ["Web Development Club", "Student Council"],
                  },
                  {
                    id: "s103",
                    name: "Charlie Brown",
                    fullName: "Charlie Brown",
                    nickname: "Charlie",
                    age: 18,
                    birthday: "2006-01-10",
                    address: "789 Code Lane, Toledo City",
                    email: "charlie.brown@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6803",
                    department: "College",
                    yearLevel: "1st Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block A",
                    dreamJob: "Software Engineer",
                    fatherGuardianName: "Charles Brown Sr.",
                    motherGuardianName: "Lucy Brown",
                    socialMediaFacebook: "charlie.brown.tech",
                    socialMediaInstagram: "@charliebrown",
                    socialMediaTwitter: "@charlie_tech",
                    sayingMotto: "Tech enthusiast.",
                    image: "/placeholder.svg",
                    profilePictureUrl: "/placeholder.svg",
                    quote: "Tech enthusiast.",
                    achievements: ["Honor Student"],
                    activities: ["Tech Club"],
                  },
                  {
                    id: "s104",
                    name: "Diana Miller",
                    fullName: "Diana Miller",
                    nickname: "Di",
                    age: 19,
                    birthday: "2005-09-05",
                    address: "321 Future St, Toledo City",
                    email: "diana.miller@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6804",
                    department: "College",
                    yearLevel: "1st Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block A",
                    dreamJob: "Software Engineer",
                    fatherGuardianName: "David Miller",
                    motherGuardianName: "Diana Miller Sr.",
                    socialMediaFacebook: "diana.miller.future",
                    socialMediaInstagram: "@dianamiller",
                    socialMediaTwitter: "@diana_codes",
                    sayingMotto: "Future software engineer.",
                    image: "/placeholder.svg",
                    profilePictureUrl: "/placeholder.svg",
                    quote: "Future software engineer.",
                    achievements: ["Academic Excellence"],
                    activities: ["Programming Society"],
                  },
                  {
                    id: "s105",
                    name: "Eve Davis",
                    fullName: "Eve Davis",
                    nickname: "Evie",
                    age: 18,
                    birthday: "2006-04-20",
                    address: "654 Algorithm Ave, Toledo City",
                    email: "eve.davis@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6805",
                    department: "College",
                    yearLevel: "1st Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block A",
                    dreamJob: "Data Scientist",
                    fatherGuardianName: "Edward Davis",
                    motherGuardianName: "Eva Davis",
                    socialMediaFacebook: "eve.davis.algorithms",
                    socialMediaInstagram: "@evedavis",
                    socialMediaTwitter: "@eve_algorithms",
                    sayingMotto: "Passionate about algorithms.",
                    image: "/placeholder.svg",
                    profilePictureUrl: "/placeholder.svg",
                    quote: "Passionate about algorithms.",
                    achievements: ["Math Excellence Award"],
                    activities: ["Algorithm Study Group"],
                  },
                  {
                    id: "s106",
                    name: "Frank White",
                    fullName: "Frank White",
                    nickname: "Frank",
                    age: 19,
                    birthday: "2005-08-25",
                    address: "567 Tech Blvd, Toledo City",
                    email: "frank.white@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6806",
                    department: "College",
                    yearLevel: "1st Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block A",
                    dreamJob: "Data Analyst",
                    fatherGuardianName: "William White",
                    motherGuardianName: "Mary White",
                    socialMediaFacebook: "frank.white.tech",
                    socialMediaInstagram: "@frankwhite",
                    socialMediaTwitter: "@frank_tech",
                    sayingMotto: "Always learning new tech.",
                    image: "/placeholder.svg",
                    profilePictureUrl: "/placeholder.svg",
                    quote: "Always learning new tech.",
                    achievements: ["Data Analysis Project Winner"],
                    activities: ["Data Science Club"],
                  },
                  {
                    id: "s107",
                    name: "Grace Taylor",
                    fullName: "Grace Taylor",
                    nickname: "Grace",
                    age: 18,
                    birthday: "2006-05-01",
                    address: "890 Design St, Toledo City",
                    email: "grace.taylor@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6807",
                    department: "College",
                    yearLevel: "1st Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block A",
                    dreamJob: "UX Designer",
                    fatherGuardianName: "Taylor Taylor",
                    motherGuardianName: "Grace Taylor Sr.",
                    socialMediaFacebook: "grace.taylor.design",
                    socialMediaInstagram: "@gracetaylor",
                    socialMediaTwitter: "@grace_design",
                    sayingMotto: "Designing user experiences.",
                    image: "/placeholder.svg",
                    profilePictureUrl: "/placeholder.svg",
                    quote: "Designing user experiences.",
                    achievements: ["Design Competition Winner"],
                    activities: ["Design Society"],
                  },
                  {
                    id: "s108",
                    name: "Henry Wilson",
                    fullName: "Henry Wilson",
                    nickname: "Henry",
                    age: 19,
                    birthday: "2005-06-15",
                    address: "901 Problem Solving Rd, Toledo City",
                    email: "henry.wilson@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6808",
                    department: "College",
                    yearLevel: "1st Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block A",
                    dreamJob: "Software Developer",
                    fatherGuardianName: "Henry Wilson Sr.",
                    motherGuardianName: "Linda Wilson",
                    socialMediaFacebook: "henry.wilson.solve",
                    socialMediaInstagram: "@henrywilson",
                    socialMediaTwitter: "@henry_solve",
                    sayingMotto: "Problem solver.",
                    image: "/placeholder.svg",
                    profilePictureUrl: "/placeholder.svg",
                    quote: "Problem solver.",
                    achievements: ["Problem Solving Challenge Winner"],
                    activities: ["Problem Solving Club"],
                  },
                  {
                    id: "s109",
                    name: "Ivy Moore",
                    fullName: "Ivy Moore",
                    nickname: "Ivy",
                    age: 18,
                    birthday: "2006-07-05",
                    address: "102 Cybersecurity Blvd, Toledo City",
                    email: "ivy.moore@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6809",
                    department: "College",
                    yearLevel: "1st Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block A",
                    dreamJob: "Cybersecurity Analyst",
                    fatherGuardianName: "Moore Moore",
                    motherGuardianName: "Ivy Moore Sr.",
                    socialMediaFacebook: "ivy.moore.cyber",
                    socialMediaInstagram: "@ivymoore",
                    socialMediaTwitter: "@ivy_cyber",
                    sayingMotto: "Cybersecurity advocate.",
                    image: "/placeholder.svg",
                    profilePictureUrl: "/placeholder.svg",
                    quote: "Cybersecurity advocate.",
                    achievements: ["Cybersecurity Competition Finalist"],
                    activities: ["Cybersecurity Club"],
                  },
                  {
                    id: "s110",
                    name: "Jack Green",
                    fullName: "Jack Green",
                    nickname: "Jack",
                    age: 19,
                    birthday: "2005-04-30",
                    address: "203 Data Science St, Toledo City",
                    email: "jack.green@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6810",
                    department: "College",
                    yearLevel: "1st Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block A",
                    dreamJob: "Data Scientist",
                    fatherGuardianName: "Green Green",
                    motherGuardianName: "Jackie Green",
                    socialMediaFacebook: "jack.green.data",
                    socialMediaInstagram: "@jackgreen",
                    socialMediaTwitter: "@jack_data",
                    sayingMotto: "Aspiring data scientist.",
                    image: "/placeholder.svg",
                    profilePictureUrl: "/placeholder.svg",
                    quote: "Aspiring data scientist.",
                    achievements: ["Data Science Project Winner"],
                    activities: ["Data Science Club"],
                  },
                  {
                    id: "s111",
                    name: "Austine Kino C. Martinez",
                    fullName: "Austine Kino C. Martinez",
                    nickname: "Austine",
                    age: 19,
                    birthday: "2005-08-10",
                    address: "789 Tech Lane, Toledo City",
                    email: "austine.martinez@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6811",
                    department: "College",
                    yearLevel: "1st Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block A",
                    dreamJob: "Network Engineer",
                    fatherGuardianName: "Carlos Martinez",
                    motherGuardianName: "Kino Martinez",
                    socialMediaFacebook: "austine.martinez",
                    socialMediaInstagram: "@austinemartinez",
                    socialMediaTwitter: "@austine_tech",
                    sayingMotto: "Aspiring network engineer",
                    image: "/placeholder.svg",
                    profilePictureUrl: "/placeholder.svg",
                    quote: "Aspiring network engineer",
                    honors: "Dean's Lister",
                    achievements: ["Dean's Lister"],
                    activities: ["Networking Club"],
                  },
                ],
                officers: [
                  {
                    id: "s101",
                    name: "John Louise Bergabena",
                    image: "/placeholder.svg",
                    position: "Mayor",
                    quote: "Leading with code.",
                    honors: "Dean's Lister",
                  },
                  {
                    id: "s102",
                    name: "Vanni Louise Tanutan",
                    image: "/placeholder.svg",
                    position: "Vice Mayor",
                    quote: "Supporting the team.",
                    honors: "Dean's Lister",
                  },
                  {
                    id: "s111",
                    name: "Austine Kino C. Martinez",
                    image: "/placeholder.svg",
                    position: "Secretary",
                    quote: "Uhay",
                    honors: "Dean's Lister",
                  },
                ],
                activities: [
                  {
                    id: "a1",
                    title: "Hackathon 2024",
                    image: "/placeholder.svg",
                    description: "Annual coding competition.",
                    date: "Oct 20, 2024",
                  },
                  {
                    id: "a2",
                    title: "IT Week Celebration",
                    image: "/placeholder.svg",
                    description: "A week of tech talks and workshops.",
                    date: "Nov 15-19, 2024",
                  },
                ],
              },
              "2023-2024": {
                academicYear: "2023-2024",
                advisers: [
                  {
                    id: "prof-jones",
                    name: "Prof. Emily Jones",
                    image: "/placeholder.svg",
                    quote: "Empowering the next generation of IT professionals.",
                  },
                ],
                students: [
                  {
                    id: "s201",
                    name: "Karen Hall",
                    image: "/placeholder.svg",
                    quote: "Innovating for a better tomorrow.",
                  },
                  { id: "s202", name: "Liam King", image: "/placeholder.svg", quote: "Driven by technology." },
                  {
                    id: "s203",
                    name: "Mia Wright",
                    image: "/placeholder.svg",
                    quote: "Passionate about web development.",
                  },
                  {
                    id: "s204",
                    name: "Noah Scott",
                    image: "/placeholder.svg",
                    quote: "Exploring AI and machine learning.",
                  },
                  {
                    id: "s205",
                    name: "Olivia Adams",
                    image: "/placeholder.svg",
                    quote: "Creating impactful software.",
                  },
                ],
                officers: [],
                activities: [],
              },
            },
          },
          "block-b": {
            name: "Block B",
            schoolYears: {
              "2024-2025": {
                academicYear: "2024-2025",
                advisers: [
                  {
                    id: "prof-jones",
                    name: "Prof. Emily Jones",
                    image: "/placeholder.svg",
                    quote: "Empowering the next generation of IT professionals.",
                  },
                ],
                students: [
                  {
                    id: "s111",
                    name: "Karen Hall",
                    image: "/placeholder.svg",
                    quote: "Innovating for a better tomorrow.",
                  },
                  { id: "s112", name: "Liam King", image: "/placeholder.svg", quote: "Driven by technology." },
                  {
                    id: "s113",
                    name: "Mia Wright",
                    image: "/placeholder.svg",
                    quote: "Passionate about web development.",
                  },
                  {
                    id: "s114",
                    name: "Noah Scott",
                    image: "/placeholder.svg",
                    quote: "Exploring AI and machine learning.",
                  },
                  {
                    id: "s115",
                    name: "Olivia Adams",
                    image: "/placeholder.svg",
                    quote: "Creating impactful software.",
                  },
                ],
                officers: [],
                activities: [],
              },
            },
          },
        },
      },
      "2nd-year": {
        name: "2nd Year",
        blocks: {
          "block-a": {
            name: "Block A",
            schoolYears: {
              "2024-2025": {
                academicYear: "2024-2025",
                advisers: [
                  {
                    id: "prof-martinez-2nd",
                    name: "Prof. Carlos Martinez",
                    image: "/placeholder.svg",
                    quote: "Building on fundamentals.",
                  },
                ],
                students: [
                  {
                    id: "s201",
                    name: "Alex Chen",
                    fullName: "Alex Chen",
                    nickname: "Alex",
                    age: 19,
                    birthday: "2005-03-15",
                    address: "123 Tech Street, Toledo City",
                    email: "alex.chen@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6801",
                    department: "College",
                    yearLevel: "2nd Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block A",
                    dreamJob: "Software Developer",
                    fatherGuardianName: "Robert Chen",
                    motherGuardianName: "Maria Chen",
                    socialMediaFacebook: "alex.chen.dev",
                    socialMediaInstagram: "@alexchen",
                    socialMediaTwitter: "@alex_codes",
                    sayingMotto: "Building the future with code.",
                    image: "/placeholder.svg",
                    profilePictureUrl: "/placeholder.svg",
                    quote: "Building the future with code.",
                    honors: "Dean's Lister",
                    achievements: ["Dean's Lister", "Programming Competition Winner"],
                    activities: ["IT Society Member", "Coding Club"],
                  },
                  {
                    id: "s202",
                    name: "Bella Rodriguez",
                    fullName: "Bella Rodriguez",
                    nickname: "Bella",
                    age: 20,
                    birthday: "2004-07-22",
                    address: "456 Innovation Ave, Toledo City",
                    email: "bella.rodriguez@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6802",
                    department: "College",
                    yearLevel: "2nd Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block A",
                    dreamJob: "Web Developer",
                    fatherGuardianName: "John Rodriguez",
                    motherGuardianName: "Sarah Rodriguez",
                    socialMediaFacebook: "bella.rodriguez.web",
                    socialMediaInstagram: "@bellarodriguez",
                    socialMediaTwitter: "@bella_web",
                    sayingMotto: "Creating beautiful web experiences.",
                    image: "/placeholder.svg",
                    profilePictureUrl: "/placeholder.svg",
                    quote: "Creating beautiful web experiences.",
                    achievements: ["Web Design Contest Winner"],
                    activities: ["Web Development Club", "Student Council"],
                  },
                  {
                    id: "s203",
                    name: "Carlos Silva",
                    fullName: "Carlos Silva",
                    nickname: "Carlos",
                    age: 19,
                    birthday: "2005-01-10",
                    address: "789 Code Lane, Toledo City",
                    email: "carlos.silva@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6803",
                    department: "College",
                    yearLevel: "2nd Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block A",
                    dreamJob: "Software Engineer",
                    fatherGuardianName: "Carlos Silva Sr.",
                    motherGuardianName: "Lucy Silva",
                    socialMediaFacebook: "carlos.silva.tech",
                    socialMediaInstagram: "@carlossilva",
                    socialMediaTwitter: "@carlos_tech",
                    sayingMotto: "Tech enthusiast.",
                    image: "/placeholder.svg",
                    profilePictureUrl: "/placeholder.svg",
                    quote: "Tech enthusiast.",
                    achievements: ["Honor Student"],
                    activities: ["Tech Club"],
                  },
                ],
                officers: [
                  {
                    id: "s201",
                    name: "Alex Chen",
                    image: "/placeholder.svg",
                    position: "Mayor",
                    quote: "Leading with innovation.",
                    honors: "Dean's Lister",
                  },
                  {
                    id: "s202",
                    name: "Bella Rodriguez",
                    image: "/placeholder.svg",
                    position: "Vice Mayor",
                    quote: "Supporting the team.",
                    honors: "Dean's Lister",
                  },
                ],
                activities: [
                  {
                    id: "a2nd-1",
                    title: "Tech Innovation Summit",
                    image: "/placeholder.svg",
                    description: "Annual technology showcase.",
                    date: "Oct 25, 2024",
                  },
                  {
                    id: "a2nd-2",
                    title: "Programming Bootcamp",
                    image: "/placeholder.svg",
                    description: "Intensive coding workshop.",
                    date: "Nov 20-24, 2024",
                  },
                ],
              },
            },
          },
          "block-b": {
            name: "Block B",
            schoolYears: {
              "2024-2025": {
                academicYear: "2024-2025",
                advisers: [
                  {
                    id: "prof-garcia-2nd",
                    name: "Prof. Maria Garcia",
                    image: "/placeholder.svg",
                    quote: "Advancing technical skills.",
                  },
                ],
                students: [
                  {
                    id: "s211",
                    name: "David Kim",
                    image: "/placeholder.svg",
                    quote: "Exploring new technologies.",
                  },
                  {
                    id: "s212",
                    name: "Elena Wang",
                    image: "/placeholder.svg",
                    quote: "Passionate about data science.",
                  },
                  {
                    id: "s213",
                    name: "Frank Liu",
                    image: "/placeholder.svg",
                    quote: "Building scalable systems.",
                  },
                ],
                officers: [],
                activities: [],
              },
            },
          },
        },
      },
      "3rd-year": {
        name: "3rd Year",
        blocks: {
          "block-a": {
            name: "Block A",
            schoolYears: {
              "2024-2025": {
                academicYear: "2024-2025",
                advisers: [
                  {
                    id: "prof-wilson-3rd",
                    name: "Prof. James Wilson",
                    image: "/placeholder.svg",
                    quote: "Preparing for professional success.",
                  },
                ],
                students: [
                  {
                    id: "s301",
                    name: "Grace Thompson",
                    fullName: "Grace Thompson",
                    nickname: "Grace",
                    age: 20,
                    birthday: "2004-03-15",
                    address: "123 Advanced Street, Toledo City",
                    email: "grace.thompson@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6801",
                    department: "College",
                    yearLevel: "3rd Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block A",
                    dreamJob: "Senior Software Developer",
                    fatherGuardianName: "Robert Thompson",
                    motherGuardianName: "Maria Thompson",
                    socialMediaFacebook: "grace.thompson.senior",
                    socialMediaInstagram: "@gracethompson",
                    socialMediaTwitter: "@grace_senior",
                    sayingMotto: "Leading with technical excellence.",
                    image: "/placeholder.svg",
                    profilePictureUrl: "/placeholder.svg",
                    quote: "Leading with technical excellence.",
                    honors: "Dean's Lister",
                    achievements: ["Dean's Lister", "Senior Project Excellence"],
                    activities: ["IT Society Officer", "Mentorship Program"],
                  },
                  {
                    id: "s302",
                    name: "Henry Davis",
                    fullName: "Henry Davis",
                    nickname: "Henry",
                    age: 21,
                    birthday: "2003-07-22",
                    address: "456 Professional Ave, Toledo City",
                    email: "henry.davis@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6802",
                    department: "College",
                    yearLevel: "3rd Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block A",
                    dreamJob: "Tech Lead",
                    fatherGuardianName: "John Davis",
                    motherGuardianName: "Sarah Davis",
                    socialMediaFacebook: "henry.davis.lead",
                    socialMediaInstagram: "@henrydavis",
                    socialMediaTwitter: "@henry_lead",
                    sayingMotto: "Leading teams to success.",
                    image: "/placeholder.svg",
                    profilePictureUrl: "/placeholder.svg",
                    quote: "Leading teams to success.",
                    achievements: ["Leadership Award"],
                    activities: ["Leadership Development Program"],
                  },
                  {
                    id: "s303",
                    name: "Ivy Martinez",
                    fullName: "Ivy Martinez",
                    nickname: "Ivy",
                    age: 20,
                    birthday: "2004-01-10",
                    address: "789 Senior Lane, Toledo City",
                    email: "ivy.martinez@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6803",
                    department: "College",
                    yearLevel: "3rd Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block A",
                    dreamJob: "Software Architect",
                    fatherGuardianName: "Carlos Martinez",
                    motherGuardianName: "Lucy Martinez",
                    socialMediaFacebook: "ivy.martinez.architect",
                    socialMediaInstagram: "@ivymartinez",
                    socialMediaTwitter: "@ivy_architect",
                    sayingMotto: "Designing robust systems.",
                    image: "/placeholder.svg",
                    profilePictureUrl: "/placeholder.svg",
                    quote: "Designing robust systems.",
                    achievements: ["Architecture Design Award"],
                    activities: ["System Design Club"],
                  },
                ],
                officers: [
                  {
                    id: "s301",
                    name: "Grace Thompson",
                    image: "/placeholder.svg",
                    position: "Mayor",
                    quote: "Leading with excellence.",
                    honors: "Dean's Lister",
                  },
                  {
                    id: "s302",
                    name: "Henry Davis",
                    image: "/placeholder.svg",
                    position: "Vice Mayor",
                    quote: "Supporting leadership.",
                    honors: "Dean's Lister",
                  },
                ],
                activities: [
                  {
                    id: "a3rd-1",
                    title: "Senior Project Showcase",
                    image: "/placeholder.svg",
                    description: "Annual senior project presentation.",
                    date: "Oct 30, 2024",
                  },
                  {
                    id: "a3rd-2",
                    title: "Industry Partnership Day",
                    image: "/placeholder.svg",
                    description: "Networking with industry professionals.",
                    date: "Nov 25, 2024",
                  },
                ],
              },
            },
          },
          "block-b": {
            name: "Block B",
            schoolYears: {
              "2024-2025": {
                academicYear: "2024-2025",
                advisers: [
                  {
                    id: "prof-anderson-3rd",
                    name: "Prof. Lisa Anderson",
                    image: "/placeholder.svg",
                    quote: "Mentoring future professionals.",
                  },
                ],
                students: [
                  {
                    id: "s311",
                    name: "Jack Wilson",
                    image: "/placeholder.svg",
                    quote: "Preparing for industry.",
                  },
                  {
                    id: "s312",
                    name: "Kate Brown",
                    image: "/placeholder.svg",
                    quote: "Building professional networks.",
                  },
                  {
                    id: "s313",
                    name: "Leo Garcia",
                    image: "/placeholder.svg",
                    quote: "Advancing technical expertise.",
                  },
                ],
                officers: [],
                activities: [],
              },
            },
          },
        },
      },
      "4th-year": {
        name: "4th Year",
        blocks: {
          "block-d": {
            name: "Block D",
            schoolYears: {
              "2024-2025": {
                academicYear: "2024-2025",
                advisers: [],
                students: [
                  {
                    id: "s401",
                    name: "Xyril Rose I. Abanes",
                    fullName: "Xyril Rose I. Abanes",
                    nickname: "Xyril",
                    age: 22,
                    birthday: "2002-04-10",
                    address: "789 Senior Street, Toledo City",
                    email: "xyril.abanes@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6803",
                    department: "College",
                    yearLevel: "4th Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block D",
                    dreamJob: "Systems Analyst",
                    fatherGuardianName: "Ricardo Abanes",
                    motherGuardianName: "Rose Abanes",
                    socialMediaFacebook: "xyril.abanes",
                    socialMediaInstagram: "@xyrilabanes",
                    socialMediaTwitter: "@xyril_tech",
                    sayingMotto: "Excellence through perseverance.",
                    image: "/images/fpic.png",
                    profilePictureUrl: "/images/fpic.png",
                    quote: "Coding my way to success.",
                    honors: "Dean's Lister",
                    achievements: ["Dean's Lister", "Thesis Excellence Award"],
                    activities: ["IT Society Officer", "Academic Committee"],
                  },
                  {
                    id: "s402",
                    name: "Nestor E. Alegada Jr.",
                    image: "/images/mpic.png",
                    quote: "Building digital dreams.",
                  },
                  {
                    id: "s403",
                    name: "Rafael L. Aligui",
                    image: "/images/mpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  { id: "s404", name: "Lex C. Ariate", image: "/images/mpic.png", quote: "Tech enthusiast." },
                  {
                    id: "s405",
                    name: "Ferlita J. Ationg",
                    image: "/images/fpic.png",
                    quote: "Future software engineer.",
                  },
                  {
                    id: "s406",
                    name: "Marjorie T Barotag",
                    image: "/images/fpic.png",
                    quote: "Passionate about algorithms.",
                  },
                  { id: "s407", name: "Alfred Barreda", image: "/images/mpic.png", quote: "Always learning new tech." },
                  {
                    id: "s408",
                    name: "John Louise R. Bergabena",
                    image: "/images/mpic.png",
                    quote: "Designing user experiences.",
                  },
                  { id: "s409", name: "April Grace P. Cabanog", image: "/images/fpic.png", quote: "Problem solver." },
                  {
                    id: "s410",
                    name: "Sedric Norvin A. Cabiles",
                    image: "/images/mpic.png",
                    quote: "Cybersecurity advocate.",
                  },
                  {
                    id: "s411",
                    name: "Joeberth C. Canceller",
                    image: "/images/mpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s412",
                    name: "Shane Starlet C. Cano",
                    fullName: "Shane Starlet C. Cano",
                    nickname: "Shane",
                    age: 22,
                    birthday: "2002-05-12",
                    address: "890 Tech Boulevard, Toledo City",
                    email: "shane.cano@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6812",
                    department: "College",
                    yearLevel: "4th Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block D",
                    dreamJob: "Network Engineer",
                    fatherGuardianName: "Frank Cano",
                    motherGuardianName: "Starlet Cano",
                    socialMediaFacebook: "shane.cano",
                    socialMediaInstagram: "@shanecano",
                    socialMediaTwitter: "@shane_tech",
                    sayingMotto: "Aspiring network engineer",
                    image: "/images/fpic.png",
                    profilePictureUrl: "/images/fpic.png",
                    quote: "Aspiring network engineer",
                    honors: "Dean's Lister",
                    achievements: ["Dean's Lister"],
                    activities: ["Networking Club"],
                  },
                  {
                    id: "s413",
                    name: "Carl Angelo P. Codaste",
                    image: "/images/mpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s414",
                    name: "Joseph Consolacion",
                    image: "/images/mpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s415",
                    name: "Neil John Dacuma",
                    image: "/images/mpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  { id: "s416", name: "Arnel Demotor", image: "/images/mpic.png", quote: "Aspiring data scientist." },
                  {
                    id: "s417",
                    name: "Genesis Ashly D. Ebonalo",
                    image: "/images/fpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s418",
                    name: "Chyril Hadrian Gadia",
                    image: "/images/mpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s419",
                    name: "Adriane M. Gumahad",
                    image: "/images/mpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s420",
                    name: "Jose Ric D. Habaybay Jr.",
                    image: "/images/mpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s421",
                    name: "Julie Paz P. Hacbang",
                    image: "/images/fpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s422",
                    name: "Juntong Jill Cris G.",
                    fullName: "Juntong Jill Cris G.",
                    nickname: "Jill",
                    age: 22,
                    birthday: "2002-06-15",
                    address: "901 Tech Plaza, Toledo City",
                    email: "jill.cris@student.consolatrix.edu.ph",
                    phone: "+63 912 345 6813",
                    department: "College",
                    yearLevel: "4th Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block D",
                    dreamJob: "Data Scientist",
                    fatherGuardianName: "Jill Cris",
                    motherGuardianName: "Gris Cris",
                    socialMediaFacebook: "jill.cris",
                    socialMediaInstagram: "@jillcris",
                    socialMediaTwitter: "@jill_tech",
                    sayingMotto: "Uhay",
                    image: "/images/mpic.png",
                    profilePictureUrl: "/images/mpic.png",
                    quote: "Uhay",
                    honors: "Dean's Lister",
                    achievements: ["Dean's Lister"],
                    activities: ["Data Science Club"],
                  },
                  {
                    id: "s423",
                    name: "Rheffe S. Labajo",
                    image: "/images/mpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s424",
                    name: "Veejay V. Laurente",
                    image: "/images/mpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s425",
                    name: "Austine Kiño Cañete Martinez",
                    fullName: "Austine Kiño Cañete Martinez",
                    nickname: "Kin-Kin",
                    age: 21,
                    birthday: "2004-05-05",
                    address: "Dakit, Poblacion, Pinamungajan, Cebu",
                    email: "austinemartinez05@gmail.com",
                    phone: "+63 995 057 6696",
                    department: "College",
                    yearLevel: "4th Year",
                    courseProgram: "Bachelor of Science in Information Technology",
                    blockSection: "Block D",
                    dreamJob: "Network Engineer",
                    fatherGuardianName: "Adrian Martinez",
                    motherGuardianName: "Karen Martinez",
                    socialMediaFacebook: "austine.martinez.14",
                    socialMediaInstagram: "@austinemartinez",
                    socialMediaTwitter: "@austine_tech",
                    sayingMotto: "Excellence through perseverance.",
                    image: "/images/fpic.png",
                    profilePictureUrl: "/images/fpic.png",
                    quote: "Coding my way to success.",
                    honors: "Dean's Lister",
                    achievements: ["Dean's Lister", "Thesis Excellence Award"],
                    activities: ["IT Society Officer", "Academic Committee"],
                  },
                  {
                    id: "s426",
                    name: "Carl Debson Monleon",
                    image: "/images/mpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s427",
                    name: "Jubec S. Navarro",
                    image: "/images/mpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s428",
                    name: "John Michael Israel D. Olayvar",
                    image: "/images/mpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s429",
                    name: "Melbourne Horizon U. Paras",
                    image: "/images/mpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s430",
                    name: "Dave Z. Ricaplaza",
                    image: "/images/mpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s431",
                    name: "James Francis E. Rodriguez",
                    image: "/images/mpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s432",
                    name: "Chanlyn L. Sanchez",
                    image: "/images/fpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s433",
                    name: "Vanni Louise C. Tanutan",
                    image: "/images/fpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s434",
                    name: "Angelica C. Torres",
                    image: "/images/fpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s435",
                    name: "Jannah P. Villarmino",
                    image: "/images/fpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  {
                    id: "s436",
                    name: "Danilo A. Villarosa Jr.",
                    image: "/images/mpic.png",
                    quote: "Aspiring data scientist.",
                  },
                  { id: "s437", name: "Gyan Yonson", image: "/images/mpic.png", quote: "Aspiring data scientist." },
                ],
                officers: [
                  {
                    id: "s408",
                    name: "John Louise R. Bergabena",
                    image: "/images/mpic.png",
                    position: "Mayor",
                    quote: "Leading with code.",
                  },
                  {
                    id: "s433",
                    name: "Vanni Louise C. Tanutan",
                    image: "/images/fpic.png",
                    position: "Vice Mayor",
                    quote: "Supporting the team.",
                  },
                  {
                    id: "s425",
                    name: "Austine Kino C. Martinez",
                    image: "/images/mpic.png",
                    position: "Secretary",
                    quote: "Uhay",
                  },
                  {
                    id: "s432",
                    name: "Chanlyn L. Sanchez",
                    image: "/images/fpic.png",
                    position: "Assistant Secretary",
                    quote: "Uhay",
                  },
                  {
                    id: "s405",
                    name: "Ferlita J. Ationg",
                    image: "/images/fpic.png",
                    position: "Treasurer",
                    quote: "Uhay",
                  },
                ],
                activities: [
                  {
                    id: "a1",
                    title: "Hackathon 2024",
                    image: "/placeholder.svg",
                    description: "Annual coding competition.",
                    date: "Oct 20, 2024",
                  },
                  {
                    id: "a2",
                    title: "IT Week Celebration",
                    image: "/placeholder.svg",
                    description: "A week of tech talks and workshops.",
                    date: "Nov 15-19, 2024",
                  },
                ],
              },
            },
          },
        },
      },
    },
  },
  beed: {
    name: "BEED",
    fullName: "Bachelor of Elementary Education",
    years: {
      "1st-year": {
        name: "1st Year",
        blocks: {
          "block-a": {
            name: "Block A",
            schoolYears: {
              "2024-2025": {
                academicYear: "2024-2025",
                advisers: [
                  {
                    id: "beed-adv-1",
                    name: "Prof. Maria Dela Cruz",
                    image: "/placeholder.svg",
                    quote: "Inspire young minds.",
                  },
                ],
                students: [
                  { id: "beed101", name: "Ana Flores", image: "/placeholder.svg", quote: "Teaching with heart." },
                  { id: "beed102", name: "Bella Santos", image: "/placeholder.svg", quote: "Learning every day." },
                  { id: "beed103", name: "Carlo Perez", image: "/placeholder.svg", quote: "Future educator." },
                  { id: "beed104", name: "Dina Ramos", image: "/placeholder.svg", quote: "Kids are amazing." },
                  { id: "beed105", name: "Eli Cruz", image: "/placeholder.svg", quote: "Teach. Learn. Grow." },
                ],
                officers: [
                  {
                    id: "beed101",
                    name: "Ana Flores",
                    image: "/placeholder.svg",
                    position: "Mayor",
                    quote: "Lead with kindness.",
                  },
                  {
                    id: "beed103",
                    name: "Carlo Perez",
                    image: "/placeholder.svg",
                    position: "Secretary",
                    quote: "Serve with joy.",
                  },
                ],
                activities: [
                  {
                    id: "beed-a1",
                    title: "Reading Camp",
                    image: "/placeholder.svg",
                    description: "Early literacy workshop.",
                    date: "Oct 12, 2024",
                  },
                ],
              },
            },
          },
          "block-b": {
            name: "Block B",
            schoolYears: {
              "2024-2025": {
                academicYear: "2024-2025",
                advisers: [
                  {
                    id: "beed-adv-2",
                    name: "Prof. Liza Mendoza",
                    image: "/placeholder.svg",
                    quote: "Teach, touch lives.",
                  },
                ],
                students: [
                  { id: "beed111", name: "Faye Villanueva", image: "/placeholder.svg", quote: "Dream big." },
                  { id: "beed112", name: "Gino Navarro", image: "/placeholder.svg", quote: "Teach with passion." },
                  { id: "beed113", name: "Hanna Olivar", image: "/placeholder.svg", quote: "Guiding the youth." },
                ],
                officers: [],
                activities: [],
              },
            },
          },
        },
      },
    },
  },
  bsed: {
    name: "BSED",
    fullName: "Bachelor of Secondary Education",
    years: {
      "1st-year": {
        name: "1st Year",
        blocks: {
          "block-a": {
            name: "Block A",
            schoolYears: {
              "2024-2025": {
                academicYear: "2024-2025",
                advisers: [
                  {
                    id: "bsed-adv-1",
                    name: "Prof. Ramon Reyes",
                    image: "/placeholder.svg",
                    quote: "Empower learners.",
                  },
                ],
                students: [
                  { id: "bsed101", name: "Ivan Torres", image: "/placeholder.svg", quote: "Share knowledge." },
                  { id: "bsed102", name: "Jessa Lim", image: "/placeholder.svg", quote: "Guide and grow." },
                  { id: "bsed103", name: "Kyle Bautista", image: "/placeholder.svg", quote: "Teach to inspire." },
                  { id: "bsed104", name: "Lara Nunez", image: "/placeholder.svg", quote: "Every child can." },
                ],
                officers: [
                  {
                    id: "bsed102",
                    name: "Jessa Lim",
                    image: "/placeholder.svg",
                    position: "Mayor",
                    quote: "Lead by example.",
                  },
                ],
                activities: [
                  {
                    id: "bsed-a1",
                    title: "Teaching Demo Day",
                    image: "/placeholder.svg",
                    description: "Micro-teaching practice.",
                    date: "Nov 8, 2024",
                  },
                ],
              },
            },
          },
        },
      },
    },
  },
  bshm: {
    name: "BSHM",
    fullName: "Bachelor of Science in Hospitality Management",
    years: {
      "1st-year": {
        name: "1st Year",
        blocks: {
          "block-a": {
            name: "Block A",
            schoolYears: {
              "2024-2025": {
                academicYear: "2024-2025",
                advisers: [
                  {
                    id: "bshm-adv-1",
                    name: "Chef Marco Santos",
                    image: "/placeholder.svg",
                    quote: "Service with excellence.",
                  },
                ],
                students: [
                  { id: "bshm101", name: "Monica Rivera", image: "/placeholder.svg", quote: "Hospitality is love." },
                  { id: "bshm102", name: "Noel Garcia", image: "/placeholder.svg", quote: "Serve with heart." },
                  { id: "bshm103", name: "Olive Tan", image: "/placeholder.svg", quote: "Craft experiences." },
                ],
                officers: [
                  {
                    id: "bshm101",
                    name: "Monica Rivera",
                    image: "/placeholder.svg",
                    position: "Mayor",
                    quote: "Delight guests.",
                  },
                ],
                activities: [
                  {
                    id: "bshm-a1",
                    title: "Culinary Expo",
                    image: "/placeholder.svg",
                    description: "Showcase of dishes.",
                    date: "Dec 2, 2024",
                  },
                ],
              },
            },
          },
          "block-b": {
            name: "Block B",
            schoolYears: {
              "2024-2025": {
                academicYear: "2024-2025",
                advisers: [
                  {
                    id: "bshm-adv-2",
                    name: "Prof. Andrea Lopez",
                    image: "/placeholder.svg",
                    quote: "Serve and smile.",
                  },
                ],
                students: [
                  { id: "bshm111", name: "Paolo Chua", image: "/placeholder.svg", quote: "Guest first." },
                  { id: "bshm112", name: "Queenie Yap", image: "/placeholder.svg", quote: "Warm welcomes." },
                ],
                officers: [],
                activities: [],
              },
            },
          },
        },
      },
    },
  },
  bsentrep: {
    name: "BSENTREP",
    fullName: "Bachelor of Science in Entrepreneurship",
    years: {
      "1st-year": {
        name: "1st Year",
        blocks: {
          "block-a": {
            name: "Block A",
            schoolYears: {
              "2024-2025": {
                academicYear: "2024-2025",
                advisers: [
                  {
                    id: "entrep-adv-1",
                    name: "Prof. Victor Delgado",
                    image: "/placeholder.svg",
                    quote: "Build, iterate, thrive.",
                  },
                ],
                students: [
                  { id: "ent101", name: "Ruby Santos", image: "/placeholder.svg", quote: "Startup dreams." },
                  { id: "ent102", name: "Sam Ortega", image: "/placeholder.svg", quote: "Create value." },
                  { id: "ent103", name: "Tina Morales", image: "/placeholder.svg", quote: "Think different." },
                ],
                officers: [
                  {
                    id: "ent101",
                    name: "Ruby Santos",
                    image: "/placeholder.svg",
                    position: "Mayor",
                    quote: "Lead the hustle.",
                  },
                ],
                activities: [
                  {
                    id: "ent-a1",
                    title: "Pitch Night",
                    image: "/placeholder.svg",
                    description: "Business pitch showcase.",
                    date: "Nov 25, 2024",
                  },
                ],
              },
            },
          },
          "block-b": {
            name: "Block B",
            schoolYears: {
              "2024-2025": {
                academicYear: "2024-2025",
                advisers: [
                  {
                    id: "entrep-adv-2",
                    name: "Prof. Bianca Cruz",
                    image: "/placeholder.svg",
                    quote: "Ideate and execute.",
                  },
                ],
                students: [
                  { id: "ent111", name: "Uriel Gomez", image: "/placeholder.svg", quote: "Build products." },
                  { id: "ent112", name: "Vera Santos", image: "/placeholder.svg", quote: "Customer first." },
                ],
                officers: [],
                activities: [],
              },
            },
          },
        },
      },
    },
  },
  bscs: {
    name: "BSCS",
    fullName: "Bachelor of Science in Computer Science",
    years: {
      "1st-year": {
        name: "1st Year",
        blocks: {
          "block-a": {
            name: "Block A",
            schoolYears: {
              "2024-2025": {
                academicYear: "2024-2025",
                advisers: [
                  {
                    id: "prof-clark",
                    name: "Prof. Sarah Clark",
                    image: "/placeholder.svg",
                    quote: "Unlocking the power of computation.",
                  },
                ],
                students: [
                  { id: "cs101", name: "Zoe Turner", image: "/placeholder.svg", quote: "Algorithm enthusiast." },
                  {
                    id: "cs102",
                    name: "Yara Baker",
                    image: "/placeholder.svg",
                    quote: "Exploring theoretical computer science.",
                  },
                ],
                officers: [],
                activities: [],
              },
            },
          },
        },
      },
    },
  },
  bped: {
    name: "BPed",
    fullName: "Bachelor of Physical Education",
    years: {
      "1st-year": {
        name: "1st Year",
        blocks: {
          "block-a": {
            name: "Block A",
            schoolYears: {
              "2024-2025": {
                academicYear: "2024-2025",
                advisers: [
                  {
                    id: "prof-athletic",
                    name: "Prof. Michael Torres",
                    image: "/placeholder.svg",
                    quote: "Building champions in body and mind.",
                  },
                ],
                students: [
                  { id: "ped101", name: "Alex Rivera", image: "/placeholder.svg", quote: "Fitness is life." },
                  { id: "ped102", name: "Bella Cruz", image: "/placeholder.svg", quote: "Sports teach character." },
                  { id: "ped103", name: "Carlos Santos", image: "/placeholder.svg", quote: "Health and wellness advocate." },
                ],
                officers: [
                  {
                    id: "ped101",
                    name: "Alex Rivera",
                    image: "/placeholder.svg",
                    position: "Mayor",
                    quote: "Lead by example.",
                  },
                ],
                activities: [
                  {
                    id: "ped-a1",
                    title: "Sports Festival",
                    image: "/placeholder.svg",
                    description: "Annual sports competition.",
                    date: "Oct 15, 2024",
                  },
                ],
              },
            },
          },
        },
      },
    },
  },
}
